### ISSUE TITLE
HTML

### ISSUE THREAD

**Issue by Kingwizard96** [Kingwizard96/Spells#1]
# HTML

## User story 
As a bootcamp student 
I want the rework notes to be constructed on a webpage
so that I can easily find and read information

## Acceptance Criteria
GIVEN A Pre work Study Guide website
WHEN I visit the website in my browser 
THEN I see four boxes titled HTML,CSS,Git,And Javascript with associated notes listed

**Comment by Ronixa584** [comment]
I can provide you the HTML. md and CSS.md files. 
You can check my repo for that.
